[package]
name = "reth-net-common"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Types shared across network code
"""

[dependencies]
# reth
reth-primitives = { workspace = true }

# async
pin-project = { workspace = true }
tokio = { workspace = true, features = ["full"] }
