[package]
name = "reth-consensus-common"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# reth 
reth-primitives = { workspace = true }
reth-interfaces = { workspace = true }
reth-provider = { workspace = true }

[dev-dependencies]
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
assert_matches = "1.5.0"
mockall = "0.11.3"
