[package]
name = "reth-rpc"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Reth RPC implementation
"""
[dependencies]
# reth
reth-interfaces = { workspace = true }
reth-primitives = { workspace = true }
reth-rpc-api = { path = "../rpc-api" }
reth-rlp = { workspace = true }
reth-rpc-types = { workspace = true }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-network-api = { workspace = true, features = ["test-utils"] }
reth-rpc-engine-api = { path = "../rpc-engine-api" }
reth-revm = { path = "../../revm" }
reth-tasks = { workspace = true }

# eth
revm = { workspace = true, features = [
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_no_base_fee",
] }
ethers-core = { workspace = true, features = ["eip712"] }
revm-primitives = { workspace = true, features = ["serde"] }

# rpc
jsonrpsee = { version = "0.18" }
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.24"
jsonwebtoken = "8"

# async
async-trait = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tower = "0.4"
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = "0.7"
pin-project = { workspace = true }

bytes = "1.4"
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
hex = "0.4"
rand = { workspace = true }
tracing = { workspace = true }
tracing-futures = "0.2"
schnellru = "0.2"
futures = { workspace = true }

[dev-dependencies]
jsonrpsee = { version = "0.18", features = ["client"] }
