[package]
name = "reth-blockchain-tree"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for diagrams in docs
    "aquamarine",
]

[dependencies]
# reth
reth-primitives = { workspace = true }
reth-interfaces = { workspace = true }
reth-db = { path = "../storage/db" }
reth-provider = { workspace = true }

# common
parking_lot = { version = "0.12" }
lru = "0.10"
tracing = { workspace = true }

# mics
aquamarine = "0.3.0"
linked_hash_set = "0.1.4"

[dev-dependencies]
reth-db = { path = "../storage/db", features = ["test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-primitives = { workspace = true , features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
parking_lot = "0.12"
assert_matches = "1.5"
tokio = { workspace = true, features = ["macros", "sync"] }

[features]
test-utils = []
