[package]
name = "reth-rlp"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
description = "Fast RLP serialization library"
homepage.workspace = true
repository.workspace = true

[dependencies]
arrayvec = { version = "0.7", default-features = false }
auto_impl = "1"
bytes = { version = "1", default-features = false }
ethnum = { version = "1", default-features = false, optional = true }
smol_str = { version = "0.1", default-features = false, optional = true }
ethereum-types = { version = "0.14", features = ["codec"], optional = true }
revm-primitives = { workspace = true, features = ["serde"] }
reth-rlp-derive = { version = "0.1", path = "./rlp-derive", optional = true }

[dev-dependencies]
reth-rlp = { workspace = true, features = [
    "derive",
    "std",
    "ethnum",
    "ethereum-types",
    "smol_str",
] }
criterion = "0.4.0"
hex-literal = "0.3"
pprof = { version = "0.11", features = ["flamegraph", "frame-pointer", "criterion"] }

[features]
alloc = []
derive = ["reth-rlp-derive"]
std = ["alloc"]

[[bench]]
name = "bench"
harness = false
