[package]
name = "reth-primitives"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Commonly used types in reth."

[dependencies]
# reth
reth-rlp = { workspace = true, features = ["std", "derive", "ethereum-types"] }
reth-rlp-derive = { path = "../rlp/rlp-derive" }
reth-codecs = { version = "0.1.0", path = "../storage/codecs" }

revm-primitives = { workspace = true, features = ["serde"] }

# ethereum
ethers-core = { workspace = true, default-features = false }
tiny-keccak = { version = "2.0", features = ["keccak"] }
crunchy = { version = "0.2.2", default-features = false, features = ["limit_256"] }
ruint = { version = "1.7.0", features = ["primitive-types", "rlp"] }

# Bloom
fixed-hash = { version = "0.8", default-features = false, features = ["rustc-hex"] }

# crypto
secp256k1 = { workspace = true, default-features = false, features = [
    "global-context",
    "alloc",
    "recovery",
] }

# used for forkid
crc = "3"

# tracing
tracing = { workspace = true }

# tokio
tokio = { workspace = true, default-features = false, features = ["sync"] }
tokio-stream = { workspace = true }

# misc
bytes = "1.4"
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "2.1.0"
thiserror = { workspace = true }
sucds = "0.5.0"
hex = "0.4"
hex-literal = "0.3"
modular-bitfield = "0.11.2"
derive_more = "0.99"
url = "2.3"
impl-serde = "0.4.0"
once_cell = "1.17.0"
zstd = { version = "0.12", features = ["experimental"] }

# proof related
triehash = "0.8"
# See to replace hashers to simplify libraries
plain_hasher = "0.2"
hash-db = "0.15"

# arbitrary utils
arbitrary = { version = "1.1.7", features = ["derive"], optional = true }
proptest = { version = "1.0", optional = true }
proptest-derive = { version = "0.3", optional = true }
strum = { version = "0.24", features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
hex-literal = "0.3"
test-fuzz = "3.0.4"
rand = { workspace = true }
revm-primitives = { workspace = true, features = ["arbitrary"] }
arbitrary = { version = "1.1.7", features = ["derive"] }
proptest = { version = "1.0" }
proptest-derive = "0.3"

# necessary so we don't hit a "undeclared 'std'": 
# https://github.com/paradigmxyz/reth/pull/177#discussion_r1021172198 
secp256k1 = { workspace = true }
criterion = "0.4.0"
pprof = { version = "0.11", features = ["flamegraph", "frame-pointer", "criterion"] }

[features]
default = []
arbitrary = ["revm-primitives/arbitrary", "dep:arbitrary", "dep:proptest", "dep:proptest-derive"]
test-utils = []

[[bench]]
name = "recover_ecdsa_crit"
harness = false

[[bench]]
name = "trie_root"
harness = false
