[package]
name = "reth-beacon-consensus"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# reth
reth-consensus-common = { path = "../common" }
reth-primitives = { workspace = true }
reth-interfaces = { workspace = true }
reth-stages = { path = "../../stages" }
reth-db = { path = "../../storage/db" }
reth-provider = { workspace = true }
reth-rpc-types = { workspace = true }
reth-tasks = { workspace = true }
reth-payload-builder = { workspace = true }
reth-metrics = { workspace = true }

# async
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true }
futures = { workspace = true }

# misc
tracing = { workspace = true }
thiserror = { workspace = true }
schnellru = "0.2"

[dev-dependencies]
# reth
reth-payload-builder = { workspace = true, features = ["test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-stages = { path = "../../stages", features = ["test-utils"] }
reth-blockchain-tree = { path = "../../blockchain-tree", features = ["test-utils"] }
reth-db = { path = "../../storage/db", features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-tracing = { path = "../../tracing" }

assert_matches = "1.5"
