[package]
name = "reth-revm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "reth specific revm utilities"

[dependencies]
# reth 
reth-primitives = { workspace = true }
reth-interfaces = { workspace = true }
reth-provider = { workspace = true }
reth-revm-primitives = { path = "./revm-primitives" }
reth-revm-inspectors = { path = "./revm-inspectors" }
reth-consensus-common = { path = "../consensus/common" }

# revm
revm = { workspace = true }

# common
tracing = { workspace = true }

[dev-dependencies]
reth-rlp = { workspace = true }
once_cell = "1.17.0"
