[package]
name = "reth-interfaces"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
reth-codecs = { path = "../storage/codecs" }
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }
reth-network-api = { workspace = true }
# TODO(onbjerg): We only need this for [BlockBody]
reth-eth-wire = { path = "../net/eth-wire" }

# eth
revm-primitives = { workspace = true }
parity-scale-codec = { version = "3.2.1", features = ["bytes"] }

# async
async-trait = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true }

# misc
auto_impl = "1.0"
thiserror = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
arbitrary = { version = "1.1.7", features = ["derive"], optional = true }
secp256k1 = { workspace = true, default-features = false, features = [
    "alloc",
    "recovery",
    "rand",
], optional = true }
modular-bitfield = "0.11.2"
parking_lot = "0.12.1"

[dev-dependencies]
reth-db = { path = "../storage/db", features = ["test-utils"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
arbitrary = { version = "1.1.7", features = ["derive"] }
hex-literal = "0.3"
secp256k1 = { workspace = true, features = [
    "alloc",
    "recovery",
    "rand",
] }

[features]
bench = []
test-utils = ["tokio-stream/sync", "secp256k1"]
