[package]
name = "ef-tests"
version = "0.1.0"
description = "EF testing support for reth."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
ef-tests = []

[dependencies]
reth-primitives = { workspace = true }
reth-db = { path = "../../crates/storage/db", features = ["mdbx", "test-utils"] }
reth-provider = { workspace = true }
reth-stages = { path = "../../crates/stages" }
reth-rlp = { workspace = true }
reth-interfaces = { workspace = true }
reth-revm = { path = "../../crates/revm" }
tokio = "1.28.1"
walkdir = "2.3.3"
serde = "1.0.163"
serde_json = { workspace = true }
thiserror = { workspace = true }
