[package]
name = "reth-rpc-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Reth RPC interfaces
"""

[dependencies]
# reth
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }

# misc
jsonrpsee = { version = "0.18", features = ["server", "macros"] }
serde_json = { workspace = true }

[features]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
