[package]
name = "reth-payload-builder"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "reth payload builder"

[dependencies]
## reth
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }
reth-rlp = { workspace = true }
reth-interfaces = { workspace = true }
reth-revm-primitives = { path = "../../revm/revm-primitives" }
reth-metrics = { workspace = true }

## ethereum
revm-primitives = { workspace = true }

## async
tokio = { workspace = true, features = ["sync"] }
tokio-stream = { workspace = true }
futures-util = { workspace = true }

## misc
thiserror = { workspace = true }
sha2 = { version = "0.10", default-features = false }
tracing = { workspace = true }

[features]
test-utils = []
