[package]
name = "reth-provider"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Reth storage provider."

[dependencies]
# reth
reth-primitives = { workspace = true }
reth-interfaces = { workspace = true }
reth-revm-primitives = { path = "../../revm/revm-primitives" }
reth-db = { path = "../db" }
reth-trie = { path = "../../trie" }

# async
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["sync"] }

# tracing
tracing = { workspace = true }

# misc
thiserror = { workspace = true }
auto_impl = "1.0"
itertools = "0.10"
pin-project = { workspace = true }
derive_more = "0.99"
parking_lot = "0.12"

# test-utils
reth-rlp = { workspace = true, optional = true }

[dev-dependencies]
reth-db = { path = "../db", features = ["test-utils"] }
reth-primitives = { workspace = true, features = ["arbitrary", "test-utils"] }
reth-rlp = { workspace = true }
reth-trie = { path = "../../trie", features = ["test-utils"] }
parking_lot = "0.12"

[features]
bench = []
test-utils = ["reth-rlp"]
