[package]
name = "reth-tasks"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Task management"

[dependencies]

## async
tokio = { workspace = true, features = ["sync", "rt"] }
tracing-futures = "0.2"
futures-util = { workspace = true }

## misc
tracing = { workspace = true }
thiserror = { workspace = true }
dyn-clone = "1.0"

## rpc/metrics
reth-metrics = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["sync", "rt", "rt-multi-thread", "time", "macros"] }
