[package]
name = "reth-transaction-pool"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Transaction pool implementation
"""

[package.metadata.cargo-udeps.ignore]
normal = [
    # Used for diagrams in docs
    "aquamarine",
]

[dependencies]
# reth
reth-primitives = { workspace = true }
reth-provider = { workspace = true }
reth-interfaces = { workspace = true }
reth-rlp = { workspace = true }
reth-metrics = { workspace = true }

# async/futures
async-trait = { workspace = true}
futures-util = { workspace = true }
parking_lot = "0.12"
tokio = { workspace = true, default-features = false, features = ["sync"] }

# misc
aquamarine = "0.3.0"
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"], optional = true }
fnv = "1.0.7"
bitflags = "1.3"
auto_impl = "1.0"

# testing
rand = { workspace = true, optional = true }
paste = { version = "1.0", optional = true }

[dev-dependencies]
paste = "1.0"
rand = "0.8"

[features]
default = ["serde"]
serde = ["dep:serde"]
test-utils = ["rand", "paste", "serde"]
