on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: unit
jobs:
  test:
    name: test (partition ${{ matrix.partition }}/${{ strategy.job-total }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        partition: [1, 2, 3, 4]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests
        run: |
          cargo llvm-cov nextest --lcov --output-path lcov.info \
            --locked --workspace --all-features \
            --partition hash:${{ matrix.partition }}/${{ strategy.job-total }} \
            -E 'kind(lib)' -E 'kind(bin)' -E 'kind(proc-macro)'

      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: unit-tests

  eth-blockchain:
    name: ethereum / state tests (stable)
    runs-on: ubuntu-latest
    env:
      RUST_LOG: info,sync=error
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Checkout ethereum/tests
        uses: actions/checkout@v3
        with:
          repository: ethereum/tests
          path: testing/ef-tests/ethereum-tests
          submodules: recursive
          depth: 1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: Run Ethereum tests
        run: cargo nextest run --release -p ef-tests --features ef-tests

  doc-test:
    name: rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run doctests
        run: cargo test --doc --all --all-features

  unit-success:
    if: always()
    name: unit success
    runs-on: ubuntu-latest
    needs: [test, eth-blockchain, doc-test]
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}